services:
  - type: web
    name: tsunami-viz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wave_propagation_dash_app.py
    envVars:
      - key: DEBUG
        value: "False"
      - key: PORT
        sync: false
    disk:
      name: tsunami-data
      mountPath: /app/data
      sizeGB: 1 